server:
  port: 8090
  error:
    include-stacktrace: never
victor:
  jwt:
    security:
      enabled: true
    timezone: America/Mexico
    issuer: "https://www.efectivale.com.mx/"
    token:
      secret: "c3ViKjEzNXUqbzMxKm91YkwwMzA="
    excluded:
        path: "/v1/multi,/v1/otherExcluded"     