server:
  port: 8081
  error:
    include-stacktrace: never
efv:
  jwt:
    security:
      enabled: true
    timezone: America/Mexico
    issuer: 'https://www.efectivale.com.mx/'
    token:
      auth:
        path: "/v1/oauth/client_credential/accesstoken"
      expires-in: 360
    excluded:
      path: "/v1/multi,/v1/otherExcluded"  