server:
  port: 8081
  error:
    include-stacktrace: never
  servlet:
    context-path: "/api"  
spring:
   mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER     
efv:
  jwt:
    timezone: America/Mexico
    issuer: 'https://www.efectivale.com.mx/'
    token:
      auth:
        path: "/api/v1/oauth/client_credential/accesstoken"
      expires-in: 360
    excluded:
      path: "/api/v1/multi,/api/v1/otherExcluded"  